project_id = "nekqqlhrjgmyudmmewas"

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.import-products]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.chat-smart]
verify_jwt = true
