import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageUrl, productTitle, resolution = '2000x2000' } = await req.json();
    
    if (!imageUrl) {
      throw new Error('Image URL is required');
    }

    console.log('Generating white background for:', productTitle);

    const GOOGLE_GEMINI_API_KEY = Deno.env.get('GOOGLE_GEMINI_API_KEY');
    if (!GOOGLE_GEMINI_API_KEY) {
      throw new Error('GOOGLE_GEMINI_API_KEY is not configured');
    }

    // Fetch and convert image to base64
    const imgResponse = await fetch(imageUrl);
    const imgBuffer = await imgResponse.arrayBuffer();
    const base64Image = btoa(String.fromCharCode(...new Uint8Array(imgBuffer)));

    // Call Google Gemini with image editing
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GOOGLE_GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [
              { inline_data: { mime_type: 'image/jpeg', data: base64Image } },
              {
                text: `Generate a professional product photo on a pure white background (RGB 255,255,255).

QUALITY REQUIREMENTS:
- Target resolution: ${resolution} pixels (ultra high definition)
- Product perfectly centered in frame (equal margins on all sides)
- Soft, professional studio lighting with subtle shadows
- Product occupies 75-85% of frame
- Remove existing background completely
- Maintain all product details, textures, and sharpness
- Ultra sharp and clear image quality

Product: ${productTitle || 'product'}`
              }
            ]
          }],
          generationConfig: {
            responseModalities: ['image']
          }
        }),
      }
    );

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please try again in a few moments.');
      }
      const errorText = await response.text();
      console.error('Google Gemini error:', response.status, errorText);
      throw new Error(`AI generation failed: ${response.status}`);
    }

    const data = await response.json();
    const generatedBase64 = data.candidates?.[0]?.content?.parts?.[0]?.inline_data?.data;

    if (!generatedBase64) {
      throw new Error('No image generated by AI');
    }

    const generatedImageUrl = `data:image/png;base64,${generatedBase64}`;

    console.log('White background generated successfully');

    return new Response(
      JSON.stringify({ 
        success: true,
        imageUrl: generatedImageUrl 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('Error in generate-white-background:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate white background',
        success: false 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
