/**
 * Shopify Session Token (JWT) Verification
 * 
 * Verifies JWTs generated by Shopify App Bridge v4 idToken()
 * These tokens authenticate embedded app requests.
 */

export interface ShopifySessionTokenPayload {
  iss: string;  // Shop's admin domain (e.g., "https://shop.myshopify.com/admin")
  dest: string; // Shop's domain (e.g., "https://shop.myshopify.com")
  aud: string;  // App's client ID
  sub: string;  // User ID
  exp: number;  // Expiration timestamp
  nbf: number;  // Not before timestamp
  iat: number;  // Issued at timestamp
  jti: string;  // JWT ID
  sid: string;  // Session ID
  sig: string;  // Shopify signature
}

export interface VerifyResult {
  valid: boolean;
  payload?: ShopifySessionTokenPayload;
  shop?: string;
  userId?: string;
  error?: string;
}

/**
 * Verify a Shopify session token
 * 
 * @param token - The JWT from Authorization header
 * @param apiSecret - The app's API secret (from SHOPIFY_API_SECRET)
 * @param expectedAudience - The app's client ID (optional, for extra validation)
 */
export async function verifyShopifySessionToken(
  token: string,
  apiSecret: string,
  expectedAudience?: string
): Promise<VerifyResult> {
  try {
    // Split the JWT
    const parts = token.split(".");
    if (parts.length !== 3) {
      return { valid: false, error: "Invalid JWT format" };
    }

    const [headerB64, payloadB64, signatureB64] = parts;

    // Verify signature using HMAC-SHA256
    const encoder = new TextEncoder();
    const key = await crypto.subtle.importKey(
      "raw",
      encoder.encode(apiSecret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"]
    );

    const signatureInput = `${headerB64}.${payloadB64}`;
    const expectedSignature = await crypto.subtle.sign(
      "HMAC",
      key,
      encoder.encode(signatureInput)
    );

    // Convert expected signature to base64url
    const expectedSignatureB64 = base64urlEncode(new Uint8Array(expectedSignature));

    if (expectedSignatureB64 !== signatureB64) {
      return { valid: false, error: "Invalid signature" };
    }

    // Decode payload
    const payload: ShopifySessionTokenPayload = JSON.parse(
      new TextDecoder().decode(base64urlDecode(payloadB64))
    );

    // Check expiration (with 10 second grace period)
    const now = Math.floor(Date.now() / 1000);
    if (payload.exp < now - 10) {
      return { valid: false, error: "Token expired" };
    }

    // Check not-before
    if (payload.nbf > now + 10) {
      return { valid: false, error: "Token not yet valid" };
    }

    // Validate audience if provided
    if (expectedAudience && payload.aud !== expectedAudience) {
      return { valid: false, error: "Invalid audience" };
    }

    // Extract shop from dest
    const shop = payload.dest.replace("https://", "").replace("/", "");

    return {
      valid: true,
      payload,
      shop,
      userId: payload.sub,
    };
  } catch (err) {
    return { valid: false, error: `Verification failed: ${err}` };
  }
}

// Base64URL encoding/decoding helpers
function base64urlEncode(data: Uint8Array): string {
  return btoa(String.fromCharCode(...data))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function base64urlDecode(str: string): Uint8Array {
  // Add padding if needed
  const padded = str + "=".repeat((4 - (str.length % 4)) % 4);
  const base64 = padded.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(base64);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

/**
 * Extract session token from Authorization header
 */
export function extractSessionToken(authHeader: string | null): string | null {
  if (!authHeader) return null;
  
  // Support both "Bearer token" and just "token"
  if (authHeader.startsWith("Bearer ")) {
    return authHeader.slice(7);
  }
  
  return authHeader;
}
