import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  Bot, 
  Brain, 
  Zap, 
  Search, 
  FileText,
  Globe,
  Clock,
  Save,
  RefreshCw,
  Copy,
  CheckCircle2,
  Sparkles
} from "lucide-react";
import { useTranslation } from "@/lib/language";
import { useAuth } from "@/contexts/AuthContext";
import { useStore } from "@/contexts/StoreContext";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface AiAssistant {
  id: string;
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  enabled: boolean;
}

interface LlmsTxtField {
  id: string;
  label: { fr: string; en: string };
  enabled: boolean;
}

export function AeoSettings() {
  const { language } = useTranslation();
  const { user } = useAuth();
  const { selectedStore } = useStore();
  
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  
  // AI Assistants Access
  const [aiAssistants, setAiAssistants] = useState<AiAssistant[]>([
    { id: 'chatgpt', name: 'ChatGPT', icon: Bot, color: '#10b981', enabled: true },
    { id: 'claude', name: 'Claude', icon: Brain, color: '#8b5cf6', enabled: true },
    { id: 'gemini', name: 'Gemini', icon: Brain, color: '#3b82f6', enabled: true },
    { id: 'perplexity', name: 'Perplexity', icon: Search, color: '#f59e0b', enabled: true },
    { id: 'deepseek', name: 'DeepSeek', icon: Zap, color: '#ec4899', enabled: false },
  ]);
  
  // LLMs.txt Fields
  const [llmsTxtFields, setLlmsTxtFields] = useState<LlmsTxtField[]>([
    { id: 'direct_answers', label: { fr: 'Réponses directes', en: 'Direct answers' }, enabled: true },
    { id: 'articles', label: { fr: 'Articles', en: 'Articles' }, enabled: true },
    { id: 'products', label: { fr: 'Produits', en: 'Products' }, enabled: false },
    { id: 'pages', label: { fr: 'Pages', en: 'Pages' }, enabled: false },
  ]);
  
  // Language
  const [selectedLanguage, setSelectedLanguage] = useState<'fr' | 'en'>(language as 'fr' | 'en');
  
  // Scheduling
  const [regenerationFrequency, setRegenerationFrequency] = useState<'manual' | 'daily' | 'weekly'>('manual');
  
  // Generated LLMs.txt preview
  const [llmsTxtPreview, setLlmsTxtPreview] = useState("");

  const toggleAssistant = (id: string) => {
    setAiAssistants(prev => prev.map(a => 
      a.id === id ? { ...a, enabled: !a.enabled } : a
    ));
  };

  const toggleLlmsTxtField = (id: string) => {
    setLlmsTxtFields(prev => prev.map(f => 
      f.id === id ? { ...f, enabled: !f.enabled } : f
    ));
  };

  // Generate LLMs.txt preview
  useEffect(() => {
    const enabledAssistants = aiAssistants.filter(a => a.enabled).map(a => a.name);
    const enabledFields = llmsTxtFields.filter(f => f.enabled).map(f => f.id);
    
    const preview = `# LLMs.txt - Aeoreply Configuration
# Generated by NewAI for ${selectedStore?.store_name || 'Your Store'}

## Allowed AI Assistants
${enabledAssistants.map(a => `- ${a}`).join('\n')}

## Available Content Types
${enabledFields.map(f => `- ${f}`).join('\n')}

## Language
${selectedLanguage === 'fr' ? 'French' : 'English'}

## Regeneration Schedule
${regenerationFrequency === 'manual' ? 'Manual' : regenerationFrequency === 'daily' ? 'Daily' : 'Weekly'}

## API Endpoint
/api/llms.txt

## Contact
${user?.email || 'support@aeoreply.com'}
`;
    setLlmsTxtPreview(preview);
  }, [aiAssistants, llmsTxtFields, selectedLanguage, regenerationFrequency, selectedStore, user]);

  const handleSave = async () => {
    setSaving(true);
    try {
      // Save settings to database
      const settings = {
        ai_assistants: aiAssistants.filter(a => a.enabled).map(a => a.id),
        llms_txt_fields: llmsTxtFields.filter(f => f.enabled).map(f => f.id),
        language: selectedLanguage,
        regeneration_frequency: regenerationFrequency,
      };
      
      // TODO: Save to aeo_settings table
      await new Promise(r => setTimeout(r, 500)); // Simulate save
      
      toast.success(language === 'fr' ? 'Paramètres enregistrés' : 'Settings saved');
    } catch (error) {
      toast.error(language === 'fr' ? 'Erreur lors de la sauvegarde' : 'Error saving settings');
    } finally {
      setSaving(false);
    }
  };

  const copyLlmsTxt = () => {
    navigator.clipboard.writeText(llmsTxtPreview);
    setCopied(true);
    toast.success(language === 'fr' ? 'Copié dans le presse-papier' : 'Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">
            {language === 'fr' ? 'Paramètres AEO' : 'AEO Settings'}
          </h2>
          <p className="text-muted-foreground mt-1">
            {language === 'fr' 
              ? 'Configurez l\'accès des assistants IA et le fichier LLMs.txt'
              : 'Configure AI assistants access and LLMs.txt file'}
          </p>
        </div>
        <Button onClick={handleSave} disabled={saving}>
          {saving ? (
            <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Save className="h-4 w-4 mr-2" />
          )}
          {language === 'fr' ? 'Enregistrer' : 'Save'}
        </Button>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Left Column */}
        <div className="space-y-6">
          {/* AI Assistants Access */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Bot className="h-5 w-5 text-primary" />
                {language === 'fr' ? 'Accès des assistants IA' : 'AI Assistants Access'}
              </CardTitle>
              <CardDescription>
                {language === 'fr' 
                  ? 'Autorisez les IA à citer votre contenu'
                  : 'Allow AI assistants to cite your content'}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {aiAssistants.map((assistant) => {
                const Icon = assistant.icon;
                return (
                  <div 
                    key={assistant.id}
                    className="flex items-center justify-between p-3 rounded-lg border hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <div 
                        className="p-2 rounded"
                        style={{ backgroundColor: `${assistant.color}20`, color: assistant.color }}
                      >
                        <Icon className="h-4 w-4" />
                      </div>
                      <span className="font-medium">{assistant.name}</span>
                    </div>
                    <Checkbox
                      checked={assistant.enabled}
                      onCheckedChange={() => toggleAssistant(assistant.id)}
                    />
                  </div>
                );
              })}
            </CardContent>
          </Card>

          {/* Language */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Globe className="h-5 w-5 text-primary" />
                {language === 'fr' ? 'Langue' : 'Language'}
              </CardTitle>
              <CardDescription>
                {language === 'fr' 
                  ? 'Langue par défaut pour les réponses AEO'
                  : 'Default language for AEO answers'}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Select value={selectedLanguage} onValueChange={(v: 'fr' | 'en') => setSelectedLanguage(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="fr">🇫🇷 Français</SelectItem>
                  <SelectItem value="en">🇺🇸 English</SelectItem>
                </SelectContent>
              </Select>
            </CardContent>
          </Card>

          {/* Scheduling */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Clock className="h-5 w-5 text-primary" />
                {language === 'fr' ? 'Planification' : 'Scheduling'}
              </CardTitle>
              <CardDescription>
                {language === 'fr' 
                  ? 'Fréquence de régénération automatique'
                  : 'Automatic regeneration frequency'}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Select 
                value={regenerationFrequency} 
                onValueChange={(v: 'manual' | 'daily' | 'weekly') => setRegenerationFrequency(v)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="manual">
                    {language === 'fr' ? 'Manuel' : 'Manual'}
                  </SelectItem>
                  <SelectItem value="daily">
                    {language === 'fr' ? 'Quotidien' : 'Daily'}
                  </SelectItem>
                  <SelectItem value="weekly">
                    {language === 'fr' ? 'Hebdomadaire' : 'Weekly'}
                  </SelectItem>
                </SelectContent>
              </Select>
            </CardContent>
          </Card>
        </div>

        {/* Right Column */}
        <div className="space-y-6">
          {/* LLMs.txt Configuration */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                LLMs.txt
              </CardTitle>
              <CardDescription>
                {language === 'fr' 
                  ? 'Champs inclus dans le fichier LLMs.txt'
                  : 'Fields included in the LLMs.txt file'}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {llmsTxtFields.map((field) => (
                <div 
                  key={field.id}
                  className="flex items-center justify-between p-3 rounded-lg border hover:bg-muted/50 transition-colors"
                >
                  <span className="font-medium">
                    {field.label[language as 'fr' | 'en']}
                  </span>
                  <Checkbox
                    checked={field.enabled}
                    onCheckedChange={() => toggleLlmsTxtField(field.id)}
                  />
                </div>
              ))}
            </CardContent>
          </Card>

          {/* LLMs.txt Preview */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-primary" />
                  {language === 'fr' ? 'Aperçu LLMs.txt' : 'LLMs.txt Preview'}
                </CardTitle>
                <Button variant="outline" size="sm" onClick={copyLlmsTxt}>
                  {copied ? (
                    <CheckCircle2 className="h-4 w-4 mr-2 text-green-500" />
                  ) : (
                    <Copy className="h-4 w-4 mr-2" />
                  )}
                  {language === 'fr' ? 'Copier' : 'Copy'}
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <Textarea
                value={llmsTxtPreview}
                readOnly
                className="font-mono text-xs h-64 resize-none"
              />
              <p className="text-xs text-muted-foreground mt-2">
                {language === 'fr' 
                  ? 'Ce fichier sera accessible à /llms.txt sur votre domaine'
                  : 'This file will be accessible at /llms.txt on your domain'}
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
