-- Add is_ai_generated column to content_images table
ALTER TABLE public.content_images 
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Add index for efficient filtering
CREATE INDEX IF NOT EXISTS idx_content_images_ai_generated 
ON public.content_images (content_id, is_ai_generated) 
WHERE is_ai_generated = true;

-- Update existing images that were stored in our bucket (likely AI-generated)
UPDATE public.content_images
SET is_ai_generated = true
WHERE src LIKE '%generated-images%' 
   OR src LIKE '%ai_generated%' 
   OR src LIKE '%ai-generated%';

-- Comment for documentation
COMMENT ON COLUMN public.content_images.is_ai_generated IS 'True if image was generated by AI (NewAI), false if imported from Shopify';