-- Create the FREE plan for Shopify users (7 days trial, 20 optimizations)
INSERT INTO subscription_plans (
  id,
  name,
  description,
  price_monthly,
  price_yearly,
  price_monthly_eur,
  price_yearly_eur,
  max_products,
  max_optimizations_monthly,
  max_articles_monthly,
  max_chat_responses_monthly,
  max_shopify_requests_monthly,
  max_shopify_stores,
  max_campaigns,
  trial_max_optimizations,
  trial_max_products,
  trial_max_articles,
  is_active
) VALUES (
  'free',
  'Free',
  '7 days free trial with limited features',
  0,
  0,
  0,
  0,
  20,
  20,
  0,
  20,
  50,
  1,
  0,
  20,
  20,
  0,
  true
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_monthly = EXCLUDED.price_monthly,
  price_yearly = EXCLUDED.price_yearly,
  price_monthly_eur = EXCLUDED.price_monthly_eur,
  price_yearly_eur = EXCLUDED.price_yearly_eur,
  max_products = EXCLUDED.max_products,
  max_optimizations_monthly = EXCLUDED.max_optimizations_monthly,
  max_articles_monthly = EXCLUDED.max_articles_monthly,
  max_chat_responses_monthly = EXCLUDED.max_chat_responses_monthly,
  max_shopify_requests_monthly = EXCLUDED.max_shopify_requests_monthly,
  max_shopify_stores = EXCLUDED.max_shopify_stores,
  max_campaigns = EXCLUDED.max_campaigns,
  trial_max_optimizations = EXCLUDED.trial_max_optimizations,
  trial_max_products = EXCLUDED.trial_max_products,
  trial_max_articles = EXCLUDED.trial_max_articles,
  is_active = EXCLUDED.is_active;