-- Créer un plan Trial séparé qui basculera automatiquement vers Starter
INSERT INTO subscription_plans (
  id,
  name,
  description,
  price_monthly,
  price_yearly,
  max_products,
  max_optimizations_monthly,
  max_articles_monthly,
  max_campaigns,
  max_shopify_requests_monthly,
  max_chat_responses_monthly,
  max_shopify_stores,
  trial_days,
  trial_max_products,
  trial_max_optimizations,
  trial_max_articles,
  trial_max_shopify_requests,
  trial_max_chat_responses,
  is_active,
  display_order,
  features
) VALUES (
  'trial',
  'Trial',
  'Essai gratuit de 14 jours avec basculement automatique vers Starter',
  0,
  0,
  50,
  10,
  1,
  0,
  10,
  6,
  1,
  14,
  50,
  10,
  1,
  10,
  6,
  true,
  0,
  '{"support_email": true, "shopify_integration": true}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  max_products = 50,
  max_optimizations_monthly = 10,
  max_articles_monthly = 1,
  max_campaigns = 0,
  max_shopify_requests_monthly = 10,
  max_chat_responses_monthly = 6,
  max_shopify_stores = 1,
  trial_days = 14,
  trial_max_products = 50,
  trial_max_optimizations = 10,
  trial_max_articles = 1,
  trial_max_shopify_requests = 10,
  trial_max_chat_responses = 6,
  updated_at = now();