-- Add source column to product_images table
-- This distinguishes AI-generated images from Shopify imports permanently
ALTER TABLE public.product_images
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'shopify';

-- Add constraint for valid values
ALTER TABLE public.product_images
ADD CONSTRAINT product_images_source_check 
CHECK (source IN ('shopify', 'ai'));

-- Create index for efficient filtering by source
CREATE INDEX IF NOT EXISTS idx_product_images_source 
ON public.product_images (product_id, source);

-- Update existing AI-generated images to have source = 'ai'
UPDATE public.product_images
SET source = 'ai'
WHERE is_ai_generated = true;

-- Update existing Shopify images to have source = 'shopify' (ensure consistency)
UPDATE public.product_images
SET source = 'shopify'
WHERE is_ai_generated = false OR is_ai_generated IS NULL;

-- Add exported_to_shopify tracking for AI images
ALTER TABLE public.product_images
ADD COLUMN IF NOT EXISTS exported_to_shopify BOOLEAN DEFAULT false;

ALTER TABLE public.product_images
ADD COLUMN IF NOT EXISTS exported_at TIMESTAMP WITH TIME ZONE;

-- Comment for documentation
COMMENT ON COLUMN public.product_images.source IS 'Origin of image: ai (generated by NewAI) or shopify (imported from Shopify). NEVER changes after creation.';
COMMENT ON COLUMN public.product_images.exported_to_shopify IS 'True if AI image was exported to Shopify (has shopify_image_id assigned)';
COMMENT ON COLUMN public.product_images.exported_at IS 'Timestamp when AI image was exported to Shopify';