// This file is automatically generated. Keep compatibility helpers minimal.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function requestUrl(input: RequestInfo | URL): string {
  if (typeof input === 'string') return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

const CHAT_SETTINGS_MISSING_COLUMN = /Could not find the '([^']+)' column of 'chat_settings' in the schema cache/i;

async function fetchWithChatSettingsSchemaFallback(
  input: RequestInfo | URL,
  init: RequestInit | undefined,
  headers: Headers,
): Promise<Response> {
  const url = requestUrl(input);
  const method = (init?.method || (typeof Request !== 'undefined' && input instanceof Request ? input.method : 'GET')).toUpperCase();
  const isChatSettingsWrite = url.includes('/rest/v1/chat_settings') && ['POST', 'PATCH', 'PUT'].includes(method);

  if (!isChatSettingsWrite || typeof init?.body !== 'string') {
    return fetch(input, { ...init, headers });
  }

  let body = init.body;
  let lastResponse: Response | null = null;

  // A migration adds the new columns permanently. This loop is only a safety
  // net for deployments where PostgREST still has an older schema cached.
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const response = await fetch(input, { ...init, headers, body });
    lastResponse = response;

    if (response.ok || response.status !== 400) return response;

    const errorText = await response.clone().text().catch(() => '');
    const missingColumn = errorText.match(CHAT_SETTINGS_MISSING_COLUMN)?.[1];
    if (!missingColumn) return response;

    try {
      const payload = JSON.parse(body) as Record<string, unknown>;
      if (!(missingColumn in payload)) return response;

      delete payload[missingColumn];
      body = JSON.stringify(payload);
      console.warn(`[supabase] chat_settings schema cache is missing ${missingColumn}; retrying without that field`);
    } catch {
      return response;
    }
  }

  return lastResponse as Response;
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetchWithChatSettingsSchemaFallback(input, init, headers);
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
