import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, existingDescription, images, visionAnalysis } = await req.json();
    
    if (!title) {
      throw new Error('Product title is required');
    }

    console.log('Generating HTML description for:', title);

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const prompt = `Generate a high-quality, mobile-friendly HTML product description.

PRODUCT INFORMATION:
- Title: ${title}
${existingDescription ? `- Existing Description: ${existingDescription}` : '- No existing description'}
${visionAnalysis ? `- Visual Analysis: ${JSON.stringify(visionAnalysis)}` : ''}
${images?.length ? `- Available Images: ${images.length} product photos` : ''}

STRUCTURE REQUIREMENTS:
1. Hero section with main product benefit (1-2 sentences)
2. Key features grid with 4-6 highlighted benefits
3. Detailed characteristics/specifications table
4. Product highlights with icons
5. Usage or care instructions (if applicable)

TECHNICAL REQUIREMENTS:
- Use only Tailwind CSS classes (no custom CSS)
- Mobile-first responsive design
- Semantic HTML5 tags (section, article, etc.)
- Accessibility: proper heading hierarchy, ARIA labels
- Image-friendly: include placeholder divs for product images
- Clean, modern, professional design
- Use spacing utilities (p-4, mb-6, etc.)
- Use text utilities (text-lg, font-semibold, etc.)
- Use grid/flex for layouts

STYLE GUIDELINES:
- Clean and readable typography
- Proper whitespace and spacing
- Visual hierarchy with headings
- Bullet points or numbered lists for features
- Tables for specifications
- Modern color scheme using Tailwind colors

CONTENT QUALITY:
- Engaging and persuasive language
- Focus on benefits, not just features
- Customer-centric tone
- SEO-friendly but natural language
- Scannable format (headings, lists, short paragraphs)

OUTPUT FORMAT:
Return ONLY the HTML code (no markdown, no explanations).
The HTML should be ready to insert directly into a Shopify product description.
Start with a <div> wrapper and use nested semantic tags.`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please try again in a few moments.');
      }
      if (response.status === 402) {
        throw new Error('AI credits depleted. Please add credits to your workspace.');
      }
      const errorText = await response.text();
      console.error('AI gateway error:', response.status, errorText);
      throw new Error(`AI generation failed: ${response.status}`);
    }

    const data = await response.json();
    let htmlDescription = data.choices?.[0]?.message?.content;

    if (!htmlDescription) {
      throw new Error('No description generated by AI');
    }

    // Clean up the response (remove markdown code blocks if present)
    htmlDescription = htmlDescription
      .replace(/```html\n?/g, '')
      .replace(/```\n?/g, '')
      .trim();

    // Calculate basic metrics
    const characteristicsCount = (htmlDescription.match(/<li>/g) || []).length;
    const mediaCount = images?.length || 0;

    console.log('HTML description generated successfully');

    return new Response(
      JSON.stringify({ 
        success: true,
        htmlDescription,
        characteristicsCount,
        mediaCount,
        mobileOptimized: true,
        wordCount: htmlDescription.split(/\s+/).length
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('Error in generate-product-description-html:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate product description',
        success: false 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
